name: Dependabot - Auto-Merge
on:
  pull_request_target:

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto-merge:
    runs-on: [ ubuntu-latest ]
    name: Auto-Merge
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Fetch Metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.2.0
        with:
          github-token: ${{ secrets.ACTION_PAT }}
      
      - name: Enable Auto-Merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
      
      - name: Approve PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
